pipelines:
  test_file_file:
    input:
      type: file
      persistence_mode: async
      watching_dir: SOME_DIR
      offsets_file: SOME_FILE
      offsets_op: reset
    actions:
      - type: discard
        match_fields:
          should_drop: ok
        match_mode: or
      - type: join
        field: log
        start: '/^(panic:)|(http: panic serving)/'
        continue: '/(^$)|(goroutine [0-9]+ \[)|(\([0-9]+x[0-9,a-f]+)|(\.go:[0-9]+ \+[0-9]x)|(\/.*\.go:[0-9]+)|(\(...\))|(main\.main\(\))|(created by .*\/.*\.)|(^\[signal)|(panic.+[0-9]x[0-9,a-f]+)|(panic:)/'
        match_fields:
          stream: stderr
    output:
      type: file
