name: CD

on:
  release:
    types: published

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        app_image: [ '', 'ubuntu20.04', 'ubuntu22.04' ]
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: set-version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.VERSION }}
            APP_IMAGE=${{ matrix.app_image }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.set-version.outputs.VERSION }}-${{ matrix.app_image }}
