name: CD

on:
  release:
    types: published
  pull_request:
    branches: [ master ]

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      packages: write
      contents: read
    strategy:
      fail-fast: false
      matrix:
        image:
          - name: 'ubuntu:18.04'
            suffix: '-ubuntu18.04'
          - name: 'ubuntu:20.04'
            suffix: '-ubuntu20.04'
          - name: 'ubuntu:22.04'
            suffix: '-ubuntu22.04'
          - name: 'ubuntu:latest'
            suffix: ''
    steps:
      - uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to registry
        uses: docker/login-action@v2
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set version
        id: set-version
        run: |
          VERSION=${GITHUB_REF/refs\/tags\//}
          echo "VERSION=${VERSION}" >> $GITHUB_OUTPUT
          
          # if app_image == '' then '' else '-<app_image>'
          IMAGE_TAG_SUFFIX=$([ ${{ matrix.app_image }} == '' ] && echo '' || echo -${{ matrix.app_image }})
          # replace : with ''
          IMAGE_TAG_SUFFIX=${IMAGE_TAG_SUFFIX/:/}
          echo "IMAGE_TAG_SUFFIX=${IMAGE_TAG_SUFFIX}" >> $GITHUB_OUTPUT

      - name: Build and push
        id: docker-build
        uses: docker/build-push-action@v4
        with:
          push: true
          build-args: |
            VERSION=${{ steps.set-version.outputs.VERSION }}
            APP_IMAGE=${{ matrix.app_image }}
          tags: ghcr.io/${{ github.repository_owner }}/${{ github.event.repository.name }}:${{ steps.set-version.outputs.VERSION }}${{ matrix.image.suffix }}
