name: CI

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ${{ matrix.runner }}
    strategy:
      fail-fast: false
      matrix:
        go:
          - 1.19
        arch:
          - amd64
        runner:
          - ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: ${{ matrix.go }}

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: test-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            test-${{ runner.os }}-go-

      - name: Build
        env:
          GOARCH: ${{ matrix.arch }}
          GOFLAGS: ${{ matrix.flags }}
        run: go build ./...

      - name: Test
        env:
          GOARCH: ${{ matrix.arch }}
          GOFLAGS: ${{ matrix.flags }}
          LOG_LEVEL: error
        run: go test -coverprofile=profile.out -covermode=atomic ./...

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile.out
          if-no-files-found: error
          retention-days: 1

  upload:
    runs-on: ubuntu-latest
    needs:
      - test
      - e2e_test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Download artifact
        uses: actions/download-artifact@v3
        with:
          name: coverage

      - name: Send coverage
        uses: codecov/codecov-action@v3
        with:
          files: profile.out, profile_e2e.out

  lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Lint
        uses: golangci/golangci-lint-action@v3
        with:
          version: v1.49.0
          only-new-issues: true
          args: --timeout 5m

  check-generate:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: check-generate-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            check-generate-${{ runner.os }}-go-

      - name: Generate doc
        run: make gen-doc

      - name: Generate mocks
        run: make mock

      - name: Check git diff
        run: git diff --exit-code

  check-mod:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Get Go environment
        id: go-env
        run: |
          echo "::set-output name=cache::$(go env GOCACHE)"
          echo "::set-output name=modcache::$(go env GOMODCACHE)"
      - name: Set up cache
        uses: actions/cache@v3
        with:
          path: |
            ${{ steps.go-env.outputs.cache }}
            ${{ steps.go-env.outputs.modcache }}
          key: check-mod-${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}
          restore-keys: |
            check-mod-${{ runner.os }}-go-

      - name: Download dependencies
        run: go mod download && go mod tidy

  e2e_test:
    runs-on: ubuntu-latest
    needs:
      - test
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install Go
        uses: actions/setup-go@v3
        with:
          go-version: 1.19

      - name: Create containers
        uses: isbang/compose-action@v1.4.0
        with:
          compose-file: "./e2e/kafka_file/docker-compose-kafka.yml"

      - name: Create Kafka Topic
        run: docker exec kafka_file_kafka_1 kafka-topics.sh --bootstrap-server kafka:9092 --create --topic quickstart5 --partitions 4

      - name: Run e2e tests
        run: go test ./cmd/... -coverprofile=profile_e2e.out -covermode=atomic -coverpkg=./... --tags=e2e_new -count=1 -timeout=3m

      - name: Upload artifact
        uses: actions/upload-artifact@v3
        with:
          name: coverage
          path: profile_e2e.out
          if-no-files-found: error
          retention-days: 1
